# Generated by Django 3.2.19 on 2023-06-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_project', '0002_auto_20230617_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
