# Generated by Django 3.2.19 on 2023-06-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_project', '0003_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
